version: "3.9"
services:
  worker:
    build: .
    environment:
      START_MSG: $START_MSG
      USE_CAPTION_FILTER: $USE_CAPTION_FILTER
      API_ID: $API_ID
      DATABASE_NAME: $DATABASE_NAME
      CACHE_TIME: $CACHE_TIME
      DATABASE_URI: $DATABASE_URI
      BOT_TOKEN: $BOT_TOKEN
      COLLECTION_NAME: $COLLECTION_NAME
      CHANNELS: $CHANNELS
      API_HASH: $API_HASH
      ADMINS: $ADMINS
      USERBOT_STRING_SESSION: $USERBOT_STRING_SESSION
